# Generated by Django 4.1.6 on 2025-12-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_code', models.CharField(db_index=True, max_length=15, unique=True)),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('exchange', models.CharField(choices=[('NSE', 'NSE'), ('BSE', 'BSE')], max_length=10)),
                ('isin', models.CharField(max_length=20, unique=True)),
                ('instrument_type', models.CharField(choices=[('EQ', 'Equity')], default='EQ', max_length=10)),
                ('tick_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lot_size', models.IntegerField(default=1)),
                ('is_tradable', models.BooleanField(default=True)),
                ('is_listed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='instrument',
            index=models.Index(fields=['symbol', 'exchange'], name='instruments_symbol_c40198_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='instrument',
            unique_together={('symbol', 'exchange')},
        ),
    ]
