# Generated by Django 4.1.6 on 2025-12-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='instrument_code',
            field=models.CharField(db_index=True, default='INST00001', max_length=15),
            preserve_default=False,
        ),
    ]
