# Generated by Django 4.1.6 on 2025-12-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_instrument_instrument_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='instrument_code',
            field=models.CharField(db_index=True, max_length=15, unique=True),
        ),
    ]
