# Generated by Django 4.1.6 on 2025-12-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_email_verified_user_is_mobile_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delete_status',
            field=models.BooleanField(default=False),
        ),
    ]
