# Generated by Django 4.1.6 on 2025-12-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_delete_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_code',
            field=models.CharField(db_index=True, default='USR00000', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
